baseURL = 'https://masoudkarimif.github.io/'
languageCode = 'en-us'
title = 'masoudkf'
theme = 'hello-friend'
baseurl = "/"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
paginate = 20
enableEmoji = true
googleAnalytics = "G-ZFRSZRJSCV"

[markup.goldmark.renderer]
  unsafe= true

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "masoudkf"
    subtitle = "Developer Blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "masoudkf"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
      identifier = "reads"
      name = "Reads"
      url = "/reads"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
